package Graphic;

import java.awt.Image;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

import Content.Content;
import Errors.PostError;
import Fille.IReadGrille;
import Fille.ReadGrille;
import Grille.MyGrille;
import Impl.EngineImpl;
import Impl.EnvironmentImpl;
import contracts.EngineCont;
import contracts.EnvironmentCont;
import contracts.PlayerCont;
import decorators.EngineDec;
import decorators.EnvironmentDec;
import services.EngineServ;
import services.EnvironmentServ;
import types.Cell;
import types.Command;
import types.Dir;

/**
	 *
	 * @author ghersa
	 */
	public class launch extends javax.swing.JFrame {

		    public launch() {
		        initComponents();
		     }

		    /**
		     * This method is called from within the constructor to initialize the form.
		     * WARNING: Do NOT modify this code. The content of this method is always
		     * regenerated by the Form Editor.
		     */
		    @SuppressWarnings("unchecked")
		    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
		    private void initComponents() {

		        jPanel1 = new javax.swing.JPanel();
		        Case_1__1 = new javax.swing.JPanel();
		        C_1__1 = new javax.swing.JLabel();
		        Case_0_0 = new javax.swing.JPanel();
		        C_0_0 = new javax.swing.JLabel();
		        Case_1_1 = new javax.swing.JPanel();
		        C_1_1 = new javax.swing.JLabel();
		        Case_2_0 = new javax.swing.JPanel();
		        C_2_0 = new javax.swing.JLabel();
		        Case_2_1 = new javax.swing.JPanel();
		        C_2_1 = new javax.swing.JLabel();
		        Case_3_0 = new javax.swing.JPanel();
		        C_3_0 = new javax.swing.JLabel();
		        Case_2__1 = new javax.swing.JPanel();
		        C_2__1 = new javax.swing.JLabel();
		        Case_1_0 = new javax.swing.JPanel();
		        C_1_0 = new javax.swing.JLabel();
		        Case_3_1 = new javax.swing.JPanel();
		        C_3_1 = new javax.swing.JLabel();
		        Case_3__1 = new javax.swing.JPanel();
		        C_3__1 = new javax.swing.JLabel();
		        jLabel1 = new javax.swing.JLabel();
		        jPanel2 = new javax.swing.JPanel();
		        life = new javax.swing.JProgressBar();
		        jPanel3 = new javax.swing.JPanel();
		        TurnR = new javax.swing.JLabel();
		        Forward = new javax.swing.JLabel();
		        TurnL = new javax.swing.JLabel();
		        Backward = new javax.swing.JLabel();
		        StrafeR = new javax.swing.JLabel();
		        StrafeL = new javax.swing.JLabel();
		        Open_Door = new javax.swing.JButton();
		        Close_Door = new javax.swing.JButton();



		        Open_Door.setText("Open Door");
		        Open_Door.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                Open_Door(evt);
		            }
		        });

		        Close_Door.setText("Close Door");
		        Close_Door.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                Close_Door(evt);
		            }
		        });
		        
		        Backward.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                click_Backward(evt);
		            }
		        });

		        StrafeR.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                click_StrafeR(evt);
		            }
		        });

		        StrafeL.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                click_StrafeL(evt);
		            }
		        });

		        Forward.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                click_Forward(evt);
		            }
		        });

		        TurnR.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                click_TurnR(evt);
		            }
		        });

		        TurnL.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                click_TurnL(evt);
		            }
		        });
		        
		        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		        Case_1__1.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_1__1Layout = new javax.swing.GroupLayout(Case_1__1);
		        Case_1__1.setLayout(Case_1__1Layout);
		        Case_1__1Layout.setHorizontalGroup(
		            Case_1__1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_1__1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_1__1Layout.setVerticalGroup(
		            Case_1__1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_1__1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        );

		        Case_0_0.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_0_0Layout = new javax.swing.GroupLayout(Case_0_0);
		        Case_0_0.setLayout(Case_0_0Layout);
		        Case_0_0Layout.setHorizontalGroup(
		            Case_0_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_0_0, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_0_0Layout.setVerticalGroup(
		            Case_0_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_0_0, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_1_1.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_1_1Layout = new javax.swing.GroupLayout(Case_1_1);
		        Case_1_1.setLayout(Case_1_1Layout);
		        Case_1_1Layout.setHorizontalGroup(
		            Case_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_1_1Layout.setVerticalGroup(
		            Case_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_2_0.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_2_0Layout = new javax.swing.GroupLayout(Case_2_0);
		        Case_2_0.setLayout(Case_2_0Layout);
		        Case_2_0Layout.setHorizontalGroup(
		            Case_2_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_2_0, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
		        );
		        Case_2_0Layout.setVerticalGroup(
		            Case_2_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_2_0, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_2_1.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_2_1Layout = new javax.swing.GroupLayout(Case_2_1);
		        Case_2_1.setLayout(Case_2_1Layout);
		        Case_2_1Layout.setHorizontalGroup(
		            Case_2_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_2_1Layout.setVerticalGroup(
		            Case_2_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_3_0.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_3_0Layout = new javax.swing.GroupLayout(Case_3_0);
		        Case_3_0.setLayout(Case_3_0Layout);
		        Case_3_0Layout.setHorizontalGroup(
		            Case_3_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_3_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        );
		        Case_3_0Layout.setVerticalGroup(
		            Case_3_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_3_0, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_2__1.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_2__1Layout = new javax.swing.GroupLayout(Case_2__1);
		        Case_2__1.setLayout(Case_2__1Layout);
		        Case_2__1Layout.setHorizontalGroup(
		            Case_2__1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_2__1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_2__1Layout.setVerticalGroup(
		            Case_2__1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_2__1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_1_0.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_1_0Layout = new javax.swing.GroupLayout(Case_1_0);
		        Case_1_0.setLayout(Case_1_0Layout);
		        Case_1_0Layout.setHorizontalGroup(
		            Case_1_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_1_0, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_1_0Layout.setVerticalGroup(
		            Case_1_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_1_0, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_3_1.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_3_1Layout = new javax.swing.GroupLayout(Case_3_1);
		        Case_3_1.setLayout(Case_3_1Layout);
		        Case_3_1Layout.setHorizontalGroup(
		            Case_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_3_1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_3_1Layout.setVerticalGroup(
		            Case_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_3_1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        Case_3__1.setBackground(new java.awt.Color(208, 64, 64));

		        javax.swing.GroupLayout Case_3__1Layout = new javax.swing.GroupLayout(Case_3__1);
		        Case_3__1.setLayout(Case_3__1Layout);
		        Case_3__1Layout.setHorizontalGroup(
		            Case_3__1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_3__1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
		        );
		        Case_3__1Layout.setVerticalGroup(
		            Case_3__1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(C_3__1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
		        );

		        jLabel1.setText("Realized by  : Sofiane GHERSA And Kahina FEKIR");

		        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		        jPanel1.setLayout(jPanel1Layout);
		        jPanel1Layout.setHorizontalGroup(
		            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
		                .addContainerGap(159, Short.MAX_VALUE)
		                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addGroup(jPanel1Layout.createSequentialGroup()
		                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                            .addComponent(Case_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                            .addGroup(jPanel1Layout.createSequentialGroup()
		                                .addComponent(Case_1__1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(Case_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                            .addGroup(jPanel1Layout.createSequentialGroup()
		                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                                    .addComponent(Case_2__1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                    .addComponent(Case_3__1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                                    .addComponent(Case_2_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                                    .addComponent(Case_3_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                            .addComponent(Case_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                            .addComponent(Case_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                            .addComponent(Case_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                        .addGap(186, 186, 186))
		                    .addGroup(jPanel1Layout.createSequentialGroup()
		                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
		        );
		        jPanel1Layout.setVerticalGroup(
		            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
		                .addContainerGap()
		                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
		                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(Case_3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(Case_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(Case_3__1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addComponent(Case_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(Case_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(Case_2__1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                        .addComponent(Case_1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                        .addComponent(Case_1__1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                    .addComponent(Case_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(Case_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addGap(35, 35, 35))
		        );

		        life.setBackground(new java.awt.Color(18, 31, 232));
		        life.setForeground(java.awt.Color.blue);
		        life.setValue(50);

		        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		        jPanel2.setLayout(jPanel2Layout);
		        jPanel2Layout.setHorizontalGroup(
		            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(jPanel2Layout.createSequentialGroup()
		                .addComponent(life, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addGap(0, 168, Short.MAX_VALUE))
		        );
		        jPanel2Layout.setVerticalGroup(
		            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(jPanel2Layout.createSequentialGroup()
		                .addGap(31, 31, 31)
		                .addComponent(life, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addContainerGap(57, Short.MAX_VALUE))
		        );

		        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

		        Forward.setBackground(new java.awt.Color(178, 166, 153));

		        StrafeR.setBackground(new java.awt.Color(176, 155, 135));
		        StrafeR.setForeground(new java.awt.Color(196, 221, 120));

		        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		        jPanel3.setLayout(jPanel3Layout);
		        jPanel3Layout.setHorizontalGroup(
		            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(jPanel3Layout.createSequentialGroup()
		                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addGroup(jPanel3Layout.createSequentialGroup()
		                        .addGap(132, 132, 132)
		                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                            .addComponent(TurnR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
		                            .addComponent(StrafeR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                            .addGroup(jPanel3Layout.createSequentialGroup()
		                                .addComponent(Backward, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(StrafeL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
		                            .addGroup(jPanel3Layout.createSequentialGroup()
		                                .addComponent(Forward, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(TurnL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
		                    .addGroup(jPanel3Layout.createSequentialGroup()
		                        .addGap(160, 160, 160)
		                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                                .addComponent(Close_Door)
		                                .addComponent(Open_Door))))
		                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		            );
		        jPanel3Layout.setVerticalGroup(
		            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
		                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addComponent(Close_Door)
		                .addGap(18, 18, 18)
		                .addComponent(Open_Door)
		                .addGap(73, 73, 73)
		                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addComponent(TurnL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(TurnR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(Forward, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(Backward, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(StrafeR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(StrafeL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addGap(98, 98, 98))
		        );

		        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		        getContentPane().setLayout(layout);
		        layout.setHorizontalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addGap(18, 18, 18)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                .addContainerGap())
		        );
		        layout.setVerticalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addGroup(layout.createSequentialGroup()
		                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addContainerGap())
		        );

		        pack();
		        initimage();
		    }                       

		    public static void main(String args[]) {
		        /* Set the Nimbus look and feel */
		        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		         */
		        try {
		            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		                if ("Nimbus".equals(info.getName())) {
		                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		                    break;
		                }
		            }
		        } catch (ClassNotFoundException ex) {
		            java.util.logging.Logger.getLogger(launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		        } catch (InstantiationException ex) {
		            java.util.logging.Logger.getLogger(launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		        } catch (IllegalAccessException ex) {
		            java.util.logging.Logger.getLogger(launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		            java.util.logging.Logger.getLogger(launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		        }
		        //</editor-fold>

		        /* Create and display the form */
		        java.awt.EventQueue.invokeLater(new Runnable() {
		            public void run() {
		                new launch().setVisible(true);
		               
		            }
		        });
		        
		    }
		    

		    private void Open_Door(java.awt.event.MouseEvent evt) {
		    	
		        if(PlayD.getNature(1, 0).equals(Cell.DNC) || PlayD.getNature(1, 0).equals(Cell.DWC)) {
		        	switch (PlayD.getFace()) {
					case N:
						PlayD.getEnv().OpenDoor(PlayD.getRow()-1, PlayD.getCol());
						break;
					case S:
						PlayD.getEnv().OpenDoor(PlayD.getRow()+1, PlayD.getCol());
						break;
					case E:
						PlayD.getEnv().OpenDoor(PlayD.getRow(), PlayD.getCol()+1);
						break;
					case W:
						PlayD.getEnv().OpenDoor(PlayD.getRow(), PlayD.getCol()-1);
						break;
					}
		        	
		        }
		        MettreJourMap() ;
		    } 

		    private void Close_Door(java.awt.event.MouseEvent evt) {                            

		        if(PlayD.getNature(1, 0).equals(Cell.DNO) || PlayD.getNature(1, 0).equals(Cell.DWO)) {
		        	switch (PlayD.getFace()) {
					case N:
						PlayD.getEnv().CloseDoor(PlayD.getRow()-1, PlayD.getCol());
						break;
					case S:
						PlayD.getEnv().CloseDoor(PlayD.getRow()+1, PlayD.getCol());
						break;
					case E:
						PlayD.getEnv().CloseDoor(PlayD.getRow(), PlayD.getCol()+1);
						break;
					case W:
						PlayD.getEnv().CloseDoor(PlayD.getRow(), PlayD.getCol()-1);
						break;
					}
		        	
		        }
		        MettreJourMap() ;
		    } 
		    
		    private void click_Forward(java.awt.event.MouseEvent evt) { 
		    	PlayD.setLastCom(Command.FW);
		    	engD.step();
		        MettreJourMap() ;
		    }
		    
		    private void click_Backward(java.awt.event.MouseEvent evt) { 
		    	PlayD.setLastCom(Command.BW);
		    	engD.step();
		        MettreJourMap() ;
		    }
		    
		    private void click_StrafeL(java.awt.event.MouseEvent evt) { 
		    	PlayD.setLastCom(Command.SR);
		    	engD.step();
		        MettreJourMap() ; 
		    }
		    
		    private void click_StrafeR(java.awt.event.MouseEvent evt) {   
		    	PlayD.setLastCom(Command.SL);
		    	engD.step();
		        MettreJourMap() ;
		    }
		    
		    private void click_TurnL(java.awt.event.MouseEvent evt) {  
		    	PlayD.setLastCom(Command.TR);
		    	engD.step();
		        MettreJourMap() ;
		    }
		    
		    private void click_TurnR(java.awt.event.MouseEvent evt) { 
		    	PlayD.setLastCom(Command.TL);
		    	engD.step();
		        MettreJourMap() ;
		    }
		    
		    
		    private void initimage(){
		    	
		    	Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/f.png")));                 
			    Backward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/b.png")));
			    StrafeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/l.png")));
			    StrafeR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/r.png")));
			    TurnL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/tl.png")));
			    TurnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/tr.png")));
		        
			    C_0_0.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/Deb.gif")).getImage().getScaledInstance(134, 111, Image.SCALE_DEFAULT))); 
			   

				// **************** Initial condition
			    IReadGrille Gr = new ReadGrille();
			    
				MyGrille grille = (MyGrille) Gr.getGrille(); // grille
				Content content = Gr.getCont(); // Content

				EnvironmentServ envS = new EnvironmentImpl(content);
				EnvironmentDec envD = new EnvironmentCont(envS);
				
				EngineServ engS = new EngineImpl();
				engD = new EngineCont(engS);

				// **************** treatment
				envD.init(4, 4, grille); // Init
				engD.init(envD);  
			
				
				for (int i = 0; i < engD.getEntities().size() ; i++) {
					if(engD.getEntities().get(i).getClass().getName().equals("contracts.PlayerCont"))
					PlayD = (PlayerCont) engD.getEntities().get(i);
					PlayD.init(PlayD.getEnv(), PlayD.getRow(), PlayD.getCol(), Dir.E);
				}
				
				MettreJourMap();
		    }
		    
		    private void MettreJourMap() {

		    	int tmp = 0;
		    	JLabel[] tmpLab =  {C_1__1, C_1_0, C_1_1, C_2__1, C_2_0, C_2_1, C_3__1, C_3_0, C_3_1};
		    	
				for (int H = 1; H <= 3; H++) {
					for (int W = -1; W <= 1; W++) {
						InsertImage(tmpLab[tmp], "noir.jpeg");
						if(!PlayD.isViewable(H, W)) {
							InsertImage(tmpLab[tmp], "noir.jpeg");
						}else {
							if( PlayD.getNature(H, W).equals(Cell.EMP)) {
								switch (PlayD.getContent(H, W)) {
								case monstre: InsertImage(tmpLab[tmp], "monstre.png"); break;
								case projectile: InsertImage(tmpLab[tmp], "projectile.jpg"); break;
								case pierre: InsertImage(tmpLab[tmp], "pierre.jpg"); break;
								case caisse: InsertImage(tmpLab[tmp], "caisse.jpg"); break;
								case Cow: InsertImage(tmpLab[tmp], "Cow.jpg"); break;
								default:
									break;
								}
							}else {
								
								switch (PlayD.getNature(H, W)) {
								case EMP:  break;
								case WLL: InsertImage(tmpLab[tmp], "mur.jpg"); break;
								case DNO: InsertImage(tmpLab[tmp], "PO.png"); break;
								case DWO: InsertImage(tmpLab[tmp], "PO.png"); break;
								case DNC: InsertImage(tmpLab[tmp], "PF.png"); break;
								case DWC: InsertImage(tmpLab[tmp], "PF.png"); break;
								case IN:   break;
								case OUT:   break;
								default:
									break;
								}
							}
						}
											

						tmp++;
					}
				}
		    	
		    
		    }

		    private void InsertImage(JLabel c, String img) {
		    	
		    	 c.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagery/"+img)).getImage().getScaledInstance(134, 111, Image.SCALE_DEFAULT))); 
			       
		    }
		    
		    // Variables declaration - do not modify    
		    public static javax.swing.JLabel C_0_0;
		    public static javax.swing.JLabel C_1_0;
		    public static javax.swing.JLabel C_1_1;
		    public static javax.swing.JLabel C_1__1;
		    public static javax.swing.JLabel C_2_0;
		    public static javax.swing.JLabel C_2_1;
		    public static javax.swing.JLabel C_2__1;
		    public static javax.swing.JLabel C_3_0;
		    public static javax.swing.JLabel C_3_1;
		    public static javax.swing.JLabel C_3__1;

		    private javax.swing.JButton Open_Door;
		    private javax.swing.JButton Close_Door;
		    
		    public static javax.swing.JPanel Case_0_0;
		    public static javax.swing.JPanel Case_1_0;
		    public static javax.swing.JPanel Case_1_1;
		    public static javax.swing.JPanel Case_1__1;
		    public static javax.swing.JPanel Case_2_0;
		    public static javax.swing.JPanel Case_2_1;
		    public static javax.swing.JPanel Case_2__1;
		    public static javax.swing.JPanel Case_3_0;
		    public static javax.swing.JPanel Case_3_1;
		    public static javax.swing.JPanel Case_3__1;
		    public static javax.swing.JLabel Forward;                 
		    public static javax.swing.JLabel Backward;
		    public static javax.swing.JLabel StrafeL;
		    public static javax.swing.JLabel StrafeR;
		    public static javax.swing.JLabel TurnL;
		    public static javax.swing.JLabel TurnR;
		    public static javax.swing.JLabel jLabel1;
		    public static javax.swing.JPanel jPanel1;
		    public static javax.swing.JPanel jPanel2;
		    public static javax.swing.JPanel jPanel3;
		    public static javax.swing.JProgressBar life;
		    public static EngineDec engD;	
		    public static PlayerCont PlayD = null;
		    // End of variables declaration                   
		}
